events { worker_connections 1024; }

http {
    server {
        listen 80;
        
        location / {
            add_header Content-Type application/json;
            return 200 '{"status": "UP", "service": "feedback-service-stub"}';
        }
    }
}
